// island/vue/Island.tsx
import { defineComponent, h } from "vue";
import {
  getComponentFramework,
  getComponentName,
  getComponentProps,
} from "../core/component/utils";

const Island = defineComponent({
  props: {
    component: {
      type: Object,
      required: true,
    },
    media: {
      type: String,
      default: "",
    },
    load: {
      type: Boolean,
      default: false,
    },
    visible: {
      type: Boolean,
      default: true,
    },
    loader: {
      type: Function,
      default: () => {},
    },
    tag: {
      type: String,
      default: "div",
    },
  },
  setup(props) {
    const framework = getComponentFramework(props.component);
    const componentName = getComponentName(props.component);
    const componentProps = getComponentProps(props.component, props.loader);

    const islandData = {
      media: props.media,
      load: props.load,
      visible: props.visible,
      componentName,
      props: componentProps,
    };

    return () => {
      return h(props.tag || "div", { "data-island": framework }, [
        "Island",
        h("script", {
          type: "application/island-data",
          innerHTML: JSON.stringify(islandData),
        }),
      ]);
    };
  },
});

export default Island;

// island/Island.tsx
import { ComponentType, createElement } from "react";
import { IslandOptions } from "./types";
import { getComponentName } from "./utils";

type Props<T extends ComponentType> = IslandOptions<T>;

function Island<T extends ComponentType<any>>(props: Props<T>) {
  const componentName = getComponentName(props.component);
  const data = props.loader?.({ name: componentName }) || {};

  const islandData = {
    media: props.media,
    load: props.load,
    visible: props.visible,
    componentName,
    props: data,
  };

  const el = createElement(
    props.tag || "div",
    { "data-island": "" },
    <>
      <props.component {...data} />
      <script
        type="application/island-data"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(islandData) }}
      />
    </>
  );

  return el;
}

export default Island;
